services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        environment:
            - AUTORUN_ENABLED=1
            - PHP_OPCACHE_ENABLE=1
