services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "80:8080"
    environment:
      - AUTORUN_ENABLED=true
      - PHP_OPCACHE_ENABLE=0
